### ISSUE TITLE
google_huawei_availability namespace missing causing app to be unable to build

### ISSUE THREAD

**Issue by tiltmaster** [WissamALSbenaty/Ultra-Map-Place-Picker#7]
So, with the new gradle versioning which i was forced to upgrade, and since this package is using google_huawei_availability and its extremely outdated, and I cannot use a fork since its forming me to use it from hosted, the app is unable to launch.

is there any plans to upgrade this or should i find another package?

much appreciated.

**Comment by mauriziopinotti** [comment]
I have submitted https://github.com/devdoxconnect/google_huawei_availability/pull/2 for this, although the `google_huawei_availability` project looks pretty abandoned... 

Version can be overwritten with this btw:

```yaml
dependency_overrides:
  # Waiting for https://github.com/WissamALSbenaty/Ultra-Map-Place-Picker/issues/7
  google_huawei_availability:
    git: https://github.com/easyhour/google_huawei_availability.git
```

**Comment by mauriziopinotti** [comment]
And this is also needed for `huawei_map`, take from https://github.com/HMS-Core/hms-flutter-plugin/issues/379#issuecomment-2478997449

```yaml
  # Waiting for https://github.com/HMS-Core/hms-flutter-plugin/issues/379
  huawei_map:
    git:
      url: https://github.com/HMS-Core/hms-flutter-plugin
      path: flutter-hms-map
      ref: 9d47f5aaa11d4474b37b83e42d073f05ebaa2e24
```
